// GENERATED — do not hand-edit. Regenerate with: bun run gen:catalog
// Source: https://models.dev/api.json (the same provider registry opencode uses).
// 149 providers included, 24 skipped (need a dedicated SDK/auth flow, or missing an env var/base URL/model list).
import type { CatalogEntry } from "./catalog.ts";

export const GENERATED_CATALOG: Record<string, CatalogEntry> = {
  "zhipuai": {
    label: "Zhipu AI",
    client: "openai",
    baseURL: "https://open.bigmodel.cn/api/paas/v4",
    envVar: "ZHIPU_API_KEY",
    models: ["glm-5","glm-5.1","glm-5.2","glm-5v-turbo","glm-4.5-flash","glm-4.7","glm-4.5v","glm-4.5"],
  },
  "lucidquery": {
    label: "LucidQuery",
    client: "openai",
    baseURL: "https://api.lucidquery.com/v1",
    envVar: "LUCIDQUERY_API_KEY",
    models: ["lucidquery-agi-01-frontier","lucidnova-rf1-100b","lucidquery-agi-01-swift","lucidquery-nexus-coder"],
  },
  "anyapi": {
    label: "AnyAPI",
    client: "openai",
    baseURL: "https://api.anyapi.ai/v1",
    envVar: "ANYAPI_API_KEY",
    models: ["cohere/command-r-plus-08-2024","google/gemini-2.5-flash","google/gemini-3-flash-preview","google/gemini-2.5-pro","google/gemini-3-pro-preview","google/gemini-2.5-flash-lite","mistralai/devstral-2512","mistralai/mistral-large-2512"],
  },
  "blueclaw": {
    label: "Blue Claw",
    client: "openai",
    baseURL: "https://openai.blueclaw.network/v1",
    envVar: "BLUECLAW_API_KEY",
    models: ["Qwen3.6-27B","Qwen/Qwen3.6-35B-A3B-FP8"],
  },
  "tencent-tokenhub": {
    label: "Tencent TokenHub",
    client: "openai",
    baseURL: "https://tokenhub.tencentmaas.com/v1",
    envVar: "TENCENT_TOKENHUB_API_KEY",
    models: ["hy3","hy3-preview"],
  },
  "fireworks-ai": {
    label: "Fireworks AI",
    client: "openai",
    baseURL: "https://api.fireworks.ai/inference/v1/",
    envVar: "FIREWORKS_API_KEY",
    models: ["accounts/fireworks/routers/glm-5p2-fast","accounts/fireworks/routers/kimi-k2p6-fast","accounts/fireworks/routers/kimi-k2p6-turbo","accounts/fireworks/routers/kimi-k2p7-code-fast","accounts/fireworks/routers/kimi-k3-fast","accounts/fireworks/models/qwen3p7-plus","accounts/fireworks/models/deepseek-v4-flash","accounts/fireworks/models/gpt-oss-20b"],
  },
  "wandb": {
    label: "Weights & Biases",
    client: "openai",
    baseURL: "https://api.inference.wandb.ai/v1",
    envVar: "WANDB_API_KEY",
    models: ["microsoft/Phi-4-mini-instruct","nvidia/NVIDIA-Nemotron-3-Super-120B-A12B-FP8","nvidia/NVIDIA-Nemotron-3-Ultra-550B-A55B","google/gemma-4-31B-it","zai-org/GLM-5.2","zai-org/GLM-5.1","JetBrains/Mellum2-12B-A2.5B-Instruct","Qwen/Qwen3.5-27B"],
  },
  "crossmodel": {
    label: "CrossModel",
    client: "openai",
    baseURL: "https://api.crossmodel.ai/v1",
    envVar: "CROSSMODEL_API_KEY",
    models: ["gemini/gemini-3.5-flash","gemini/gemini-2.5-flash","gemini/gemini-3-flash-preview","gemini/gemini-3.1-pro-preview","gemini/gemini-2.5-pro","gemini/gemini-2.5-flash-lite","qwen/qwen3.7-plus","qwen/qwen3.7-max"],
  },
  "llmtr": {
    label: "LLMTR",
    client: "openai",
    baseURL: "https://llmtr.com/v1",
    envVar: "LLMTR_API_KEY",
    models: ["sincap","medgemma-4b","magibu-11b-v8","qwen3-6-35b","trendyol-7b","gemma-4"],
  },
  "claudinio": {
    label: "Claudinio",
    client: "openai",
    baseURL: "https://api.claudin.io/v1",
    envVar: "CLAUDINIO_API_KEY",
    models: ["claudinio","claudius"],
  },
  "snowflake-cortex": {
    label: "Snowflake Cortex",
    client: "openai",
    baseURL: "https://${SNOWFLAKE_ACCOUNT}.snowflakecomputing.com/api/v2/cortex/v1",
    envVar: "SNOWFLAKE_ACCOUNT",
    models: ["claude-sonnet-4-6","openai-gpt-5.6-terra","openai-gpt-4.1","claude-haiku-4-5","claude-fable-5","gemini-3.1-pro","claude-opus-4-8","openai-gpt-5.1"],
  },
  "opencode-go": {
    label: "OpenCode Go",
    client: "openai",
    baseURL: "https://opencode.ai/zen/go/v1",
    envVar: "OPENCODE_API_KEY",
    models: ["qwen3.7-plus","glm-5","qwen3.5-plus","glm-5.1","mimo-v2-omni","deepseek-v4-flash","kimi-k2.5","minimax-m2.7"],
  },
  "poe": {
    label: "Poe",
    client: "openai",
    baseURL: "https://api.poe.com/v1",
    envVar: "POE_API_KEY",
    models: ["stabilityai/stablediffusionxl","fireworks-ai/kimi-k2.5-fw","topazlabs-co/topazlabs","google/imagen-4-fast","google/gemini-3.5-flash","google/gemini-2.5-flash","google/imagen-3","google/gemini-3.1-pro"],
  },
  "baseten": {
    label: "Baseten",
    client: "openai",
    baseURL: "https://inference.baseten.co/v1",
    envVar: "BASETEN_API_KEY",
    models: ["nvidia/Nemotron-120B-A12B","nvidia/NVIDIA-Nemotron-3-Ultra-550B-A55B","thinkingmachines/inkling","zai-org/GLM-5","zai-org/GLM-5.2-Fast","zai-org/GLM-5.2","zai-org/GLM-5.1","zai-org/GLM-4.7"],
  },
  "nvidia": {
    label: "Nvidia",
    client: "openai",
    baseURL: "https://integrate.api.nvidia.com/v1",
    envVar: "NVIDIA_API_KEY",
    models: ["microsoft/phi-4-mini-instruct","microsoft/phi-4-multimodal-instruct","nvidia/magpie-tts-zeroshot","nvidia/nv-embedcode-7b-v1","nvidia/studiovoice","nvidia/sparsedrive","nvidia/cosmos-reason2-8b","nvidia/nemotron-nano-12b-v2-vl"],
  },
  "nebius": {
    label: "Nebius Token Factory",
    client: "openai",
    baseURL: "https://api.tokenfactory.nebius.com/v1",
    envVar: "NEBIUS_API_KEY",
    models: ["nvidia/nemotron-3-super-120b-a12b","nvidia/Nemotron-3-Nano-Omni","nvidia/NVIDIA-Nemotron-3-Nano-30B-A3B","nvidia/Llama-3_1-Nemotron-Ultra-253B-v1","google/gemma-3-27b-it","zai-org/GLM-5","zai-org/GLM-5.2","Qwen/Qwen3-235B-A22B-Instruct-2507"],
  },
  "vivgrid": {
    label: "Vivgrid",
    client: "openai",
    baseURL: "https://api.vivgrid.com/v1",
    envVar: "VIVGRID_API_KEY",
    models: ["gpt-5.6-sol","glm-5.2","gemini-3.1-flash-lite-preview","gpt-5.5","deepseek-v4-pro","gpt-5.4","gpt-5.2-codex","gpt-5.4-nano"],
  },
  "thinkingmachines": {
    label: "Thinking Machines",
    client: "anthropic",
    baseURL: "https://tinker.thinkingmachines.dev/services/tinker-prod/anthropic/api/v1",
    envVar: "TINKER_API_KEY",
    models: ["thinkingmachines/Inkling:peft:262144","thinkingmachines/Inkling"],
  },
  "lilac": {
    label: "Lilac",
    client: "openai",
    baseURL: "https://api.getlilac.com/v1",
    envVar: "LILAC_API_KEY",
    models: ["google/gemma-4-31b-it","zai-org/glm-5.2","moonshotai/kimi-k2.6","minimaxai/minimax-m3"],
  },
  "stepfun-ai-step-plan": {
    label: "StepFun Step Plan (Global)",
    client: "openai",
    baseURL: "https://api.stepfun.ai/step_plan/v1",
    envVar: "STEPFUN_API_KEY",
    models: ["step-3.5-flash","step-3.7-flash","step-3.5-flash-2603"],
  },
  "zhipuai-coding-plan": {
    label: "Zhipu AI Coding Plan",
    client: "openai",
    baseURL: "https://open.bigmodel.cn/api/coding/paas/v4",
    envVar: "ZHIPU_API_KEY",
    models: ["glm-5.1","glm-5v-turbo","glm-5-turbo","glm-4.7","glm-5.2","glm-4.5-air","glm-4.6v"],
  },
  "nano-gpt": {
    label: "NanoGPT",
    client: "openai",
    baseURL: "https://nano-gpt.com/api/v1",
    envVar: "NANO_GPT_API_KEY",
    models: ["ernie-5.0-thinking-preview","Baichuan4-Turbo","Gemma-4-31B-DarkIdol","qwen3.7-plus","step-2-16k-exp","Qwen3.5-27B-Omega-Evolution-v2.2-Derestricted-Lite","Qwen3.5-27B-earica-Derestricted","gemini-2.5-flash-lite-preview-06-17"],
  },
  "fastrouter": {
    label: "FastRouter",
    client: "openai",
    baseURL: "https://go.fastrouter.ai/api/v1",
    envVar: "FASTROUTER_API_KEY",
    models: ["google/veo3.1-fast","google/gemini-3.5-flash","google/gemini-2.5-flash","google/veo3.1-lite","google/gemini-3-pro-image-preview","google/gemini-3.1-flash-image-preview","google/imagen-4.0-fast","google/veo3.1"],
  },
  "nearai": {
    label: "NEAR AI Cloud",
    client: "openai",
    baseURL: "https://cloud-api.near.ai/v1",
    envVar: "NEARAI_API_KEY",
    models: ["google/gemini-3.5-flash","google/gemini-2.5-flash","google/gemini-3-pro","google/gemini-3.1-flash-lite","google/gemini-2.5-pro","google/gemini-2.5-flash-lite","google/gemma-4-31B-it","zai-org/GLM-5.1-FP8"],
  },
  "daoxe": {
    label: "DaoXE",
    client: "openai",
    baseURL: "https://daoxe.com/v1",
    envVar: "DAOXE_API_KEY",
    models: ["claude-sonnet-4-6","kimi-k2.5","claude-opus-4-8","grok-4.3","gpt-5.5","gpt-5.4","grok-4.5","claude-haiku-4-5-20251001"],
  },
  "crof": {
    label: "CrofAI",
    client: "openai",
    baseURL: "https://crof.ai/v1",
    envVar: "CROF_API_KEY",
    models: ["glm-5","glm-5.1","deepseek-v4-flash","kimi-k2.5","greg-1-mini","glm-4.7-flash","glm-5.2","qwen3.5-9b"],
  },
  "abliteration-ai": {
    label: "abliteration.ai",
    client: "openai",
    baseURL: "https://api.abliteration.ai/v1",
    envVar: "ABLIT_KEY",
    models: ["abliterated-model-large","abliterated-model"],
  },
  "alibaba-coding-plan-cn": {
    label: "Alibaba Coding Plan (China)",
    client: "openai",
    baseURL: "https://coding.dashscope.aliyuncs.com/v1",
    envVar: "ALIBABA_CODING_PLAN_API_KEY",
    models: ["qwen3.7-plus","glm-5","qwen3.5-plus","kimi-k2.5","qwen3.7-max","qwen3-coder-plus","glm-4.7","qwen3-max-2026-01-23"],
  },
  "llmgateway": {
    label: "LLM Gateway",
    client: "openai",
    baseURL: "https://api.llmgateway.io/v1",
    envVar: "LLMGATEWAY_API_KEY",
    models: ["qwen3-coder-480b-a35b-instruct","gpt-5.1-codex-mini","grok-4","mistral-small-2506","minimax-m2.7-highspeed","qwen3.7-plus","qwen3-vl-plus","grok-4-5"],
  },
  "kenari": {
    label: "Kenari",
    client: "openai",
    baseURL: "https://kenari.id/v1",
    envVar: "KENARI_API_KEY",
    models: ["gpt-image-2","mimo-v2-5","grok-4-5","grok-build-0-1","nemotron-3-nano-30b-a3b","kimi-k2-6","claude-fable-5","deepseek-v4-flash"],
  },
  "friendli": {
    label: "Friendli",
    client: "openai",
    baseURL: "https://api.friendli.ai/serverless/v1",
    envVar: "FRIENDLI_TOKEN",
    models: ["google/gemma-4-31B-it","zai-org/GLM-5.2","zai-org/GLM-5.1","Qwen/Qwen3-235B-A22B-Instruct-2507","MiniMaxAI/MiniMax-M2.5","deepseek-ai/DeepSeek-V3.2"],
  },
  "opencode": {
    label: "OpenCode Zen",
    client: "openai",
    baseURL: "https://opencode.ai/zen/v1",
    envVar: "OPENCODE_API_KEY",
    models: ["gpt-5.1-codex-mini","trinity-large-preview-free","claude-sonnet-4-6","gpt-5.5-pro","hy3-preview-free","glm-5","gemini-3.5-flash","gpt-5.3-codex-spark"],
  },
  "sakana": {
    label: "Sakana AI",
    client: "openai",
    baseURL: "https://api.sakana.ai/v1",
    envVar: "SAKANA_API_KEY",
    models: ["fugu-ultra-20260615","fugu-ultra","fugu"],
  },
  "trustedrouter": {
    label: "TrustedRouter",
    client: "openai",
    baseURL: "https://api.trustedrouter.com/v1",
    envVar: "TRUSTEDROUTER_API_KEY",
    models: ["synth","zdr","e2e","auto","cheap","synth-code","fast"],
  },
  "atomic-chat": {
    label: "Atomic Chat",
    client: "openai",
    baseURL: "http://127.0.0.1:1337/v1",
    envVar: "ATOMIC_CHAT_API_KEY",
    models: ["Qwen3_5-9B-Q4_K_M","gemma-4-E4B-it-IQ4_XS","Qwen3_5-9B-MLX-4bit","gemma-4-E4B-it-MLX-4bit","Meta-Llama-3_1-8B-Instruct-GGUF"],
  },
  "inception": {
    label: "Inception",
    client: "openai",
    baseURL: "https://api.inceptionlabs.ai/v1/",
    envVar: "INCEPTION_API_KEY",
    models: ["mercury-edit-2","mercury-2"],
  },
  "stepfun-step-plan": {
    label: "StepFun Step Plan (China)",
    client: "openai",
    baseURL: "https://api.stepfun.com/step_plan/v1",
    envVar: "STEPFUN_API_KEY",
    models: ["step-3.5-flash","step-3.7-flash","step-3.5-flash-2603","step-router-v1"],
  },
  "cloudflare-workers-ai": {
    label: "Cloudflare Workers AI",
    client: "openai",
    baseURL: "https://api.cloudflare.com/client/v4/accounts/${CLOUDFLARE_ACCOUNT_ID}/ai/v1",
    envVar: "CLOUDFLARE_ACCOUNT_ID",
    models: ["@cf/aisingapore/gemma-sea-lion-v4-27b-it","@cf/nvidia/nemotron-3-120b-a12b","@cf/google/gemma-4-26b-a4b-it","@cf/zai-org/glm-4.7-flash","@cf/zai-org/glm-5.2","@cf/qwen/qwen3-30b-a3b-fp8","@cf/qwen/qwq-32b","@cf/qwen/qwen2.5-coder-32b-instruct"],
  },
  "modelscope": {
    label: "ModelScope",
    client: "openai",
    baseURL: "https://api-inference.modelscope.cn/v1",
    envVar: "MODELSCOPE_API_KEY",
    models: ["Qwen/Qwen3-235B-A22B-Instruct-2507","Qwen/Qwen3-Coder-30B-A3B-Instruct","Qwen/Qwen3-30B-A3B-Thinking-2507","Qwen/Qwen3-30B-A3B-Instruct-2507","Qwen/Qwen3-235B-A22B-Thinking-2507","ZhipuAI/GLM-4.5","ZhipuAI/GLM-4.6"],
  },
  "github-copilot": {
    label: "GitHub Copilot",
    client: "openai",
    baseURL: "https://api.githubcopilot.com",
    envVar: "GITHUB_TOKEN",
    models: ["gemini-3.5-flash","claude-sonnet-4.6","gpt-5.6-sol","claude-fable-5","mai-code-1-flash-picker","claude-opus-4.5","gpt-5.5","gemini-3-flash-preview"],
  },
  "302ai": {
    label: "302.AI",
    client: "openai",
    baseURL: "https://api.302.ai/v1",
    envVar: "302AI_API_KEY",
    models: ["qwen3-coder-480b-a35b-instruct","grok-4.20-beta-0309-reasoning","claude-sonnet-4-6","glm-4.6v","gpt-4.1-mini","gpt-4o","glm-5","claude-haiku-4-5"],
  },
  "helicone": {
    label: "Helicone",
    client: "openai",
    baseURL: "https://ai-gateway.helicone.ai/v1",
    envVar: "HELICONE_API_KEY",
    models: ["gpt-5.1-codex-mini","grok-4","qwen2.5-coder-7b-fast","qwen3-32b","gpt-4.1-mini","gpt-4o","kimi-k2-0711","claude-3.7-sonnet"],
  },
  "alibaba-coding-plan": {
    label: "Alibaba Coding Plan",
    client: "openai",
    baseURL: "https://coding-intl.dashscope.aliyuncs.com/v1",
    envVar: "ALIBABA_CODING_PLAN_API_KEY",
    models: ["qwen3.7-plus","glm-5","qwen3.5-plus","kimi-k2.5","qwen3.7-max","qwen3-coder-plus","glm-4.7","qwen3-max-2026-01-23"],
  },
  "submodel": {
    label: "submodel",
    client: "openai",
    baseURL: "https://llm.submodel.ai/v1",
    envVar: "SUBMODEL_INSTAGEN_ACCESS_KEY",
    models: ["zai-org/GLM-4.5-Air","zai-org/GLM-4.5-FP8","Qwen/Qwen3-Coder-480B-A35B-Instruct-FP8","Qwen/Qwen3-235B-A22B-Instruct-2507","Qwen/Qwen3-235B-A22B-Thinking-2507","deepseek-ai/DeepSeek-R1-0528","deepseek-ai/DeepSeek-V3-0324","deepseek-ai/DeepSeek-V3.1"],
  },
  "neon": {
    label: "Neon",
    client: "openai",
    baseURL: "${NEON_AI_GATEWAY_BASE_URL}/v1",
    envVar: "NEON_AI_GATEWAY_BASE_URL",
    models: ["claude-sonnet-4-6","claude-haiku-4-5","gemini-3-5-flash","gemini-2-5-pro","gpt-5-4","claude-opus-4-6","claude-opus-4-8","gpt-5-4-nano"],
  },
  "ambient": {
    label: "Ambient",
    client: "openai",
    baseURL: "https://api.ambient.xyz/v1",
    envVar: "AMBIENT_API_KEY",
    models: ["zai-org/GLM-5.1-FP8","zai-org/GLM-5.2-FP8","ambient/large","deepseek/deepseek-v4-flash","xiaomi/mimo-v2.5","z-ai/glm-5.2","moonshotai/kimi-k2.6","moonshotai/kimi-k2.7-code"],
  },
  "dinference": {
    label: "DInference",
    client: "openai",
    baseURL: "https://api.dinference.com/v1",
    envVar: "DINFERENCE_API_KEY",
    models: ["glm-5","glm-5.1","glm-5.2","glm-4.7","gpt-oss-120b","minimax-m2.5"],
  },
  "privatemode-ai": {
    label: "Privatemode AI",
    client: "openai",
    baseURL: "http://localhost:8080/v1",
    envVar: "PRIVATEMODE_API_KEY",
    models: ["kimi-k2.6","whisper-large-v3","voxtral-mini-3b","gpt-oss-120b","qwen3-embedding-4b"],
  },
  "unorouter": {
    label: "UnoRouter",
    client: "openai",
    baseURL: "https://api.unorouter.com/v1",
    envVar: "UNOROUTER_API_KEY",
    models: ["step-3.7-flash:free","nemotron-3-ultra-550b-a55b:free","gpt-5.5:free","gemini-3.5-flash","deepseek-v4-flash","minimax-m2.7","claude-opus-4-8","glm-5.2"],
  },
  "frogbot": {
    label: "FrogBot",
    client: "openai",
    baseURL: "https://app.frogbot.ai/api/v1",
    envVar: "FROGBOT_API_KEY",
    models: ["claude-sonnet-4-6","gpt-4o","claude-haiku-4-5","gemini-2.5-flash","claude-opus-4-6","kimi-k2-6","kimi-k2.5","gpt-5-4-nano"],
  },
  "the-grid-ai": {
    label: "The Grid AI",
    client: "openai",
    baseURL: "https://api.thegrid.ai/v1",
    envVar: "THEGRIDAI_API_KEY",
    models: ["agent-standard","text-prime","agent-prime","code-standard","code-max","agent-max","text-max","text-standard"],
  },
  "upstage": {
    label: "Upstage",
    client: "openai",
    baseURL: "https://api.upstage.ai/v1/solar",
    envVar: "UPSTAGE_API_KEY",
    models: ["solar-pro3","solar-mini","solar-pro2"],
  },
  "cline-pass": {
    label: "ClinePass",
    client: "openai",
    baseURL: "https://api.cline.bot/api/v1",
    envVar: "CLINE_API_KEY",
    models: ["cline-pass/qwen3.7-plus","cline-pass/deepseek-v4-flash","cline-pass/glm-5.2","cline-pass/qwen3.7-max","cline-pass/kimi-k2.6","cline-pass/minimax-m3","cline-pass/deepseek-v4-pro","cline-pass/mimo-v2.5"],
  },
  "regolo-ai": {
    label: "Regolo AI",
    client: "openai",
    baseURL: "https://api.regolo.ai/v1",
    envVar: "REGOLO_API_KEY",
    models: ["qwen3.5-122b","gpt-oss-20b","qwen3.5-9b","mistral-small3.2","llama-3.3-70b-instruct","qwen3-reranker-4b","gpt-oss-120b","minimax-m2.5"],
  },
  "aiand": {
    label: "ai&",
    client: "openai",
    baseURL: "https://api.aiand.com/v1",
    envVar: "AIAND_API_KEY",
    models: ["google/gemma-4-31b-it","zai-org/glm-5.1","zai-org/glm-5.2","qwen/qwen3.6-27b","deepseek-ai/deepseek-v4-flash","deepseek-ai/deepseek-v4-pro","moonshotai/kimi-k2.6","moonshotai/kimi-k2.7-code"],
  },
  "pioneer": {
    label: "Pioneer",
    client: "openai",
    baseURL: "https://api.pioneer.ai/v1",
    envVar: "PIONEER_API_KEY",
    models: ["qwen3.7-plus","claude-sonnet-4-6","mistral-medium-3.5","gpt-4.1-mini","gpt-4o","gemini-3.5-flash","claude-haiku-4-5","claude-opus-4-6"],
  },
  "siliconflow": {
    label: "SiliconFlow",
    client: "openai",
    baseURL: "https://api.siliconflow.com/v1",
    envVar: "SILICONFLOW_API_KEY",
    models: ["google/gemma-4-26B-A4B-it","google/gemma-4-31B-it","zai-org/GLM-5","zai-org/GLM-4.5-Air","zai-org/GLM-5.2","zai-org/GLM-5.1","zai-org/GLM-5V-Turbo","tencent/Hunyuan-A13B-Instruct"],
  },
  "ai-router": {
    label: "AI-ROUTER",
    client: "openai",
    baseURL: "https://api.ai-router.dev/v1",
    envVar: "AI_ROUTER_API_KEY",
    models: ["gpt-5.6-sol","gpt-5.5","gpt-5.4","gpt-5.6-luna","gpt-5.6-terra"],
  },
  "zenmux": {
    label: "ZenMux",
    client: "openai",
    baseURL: "https://zenmux.ai/api/v1",
    envVar: "ZENMUX_API_KEY",
    models: ["kuaishou/kat-coder-pro-v2","google/gemini-3.5-flash","google/gemini-2.5-flash","google/gemini-3.1-flash-lite-preview","google/gemini-3-flash-preview","google/gemini-3.1-flash-lite","google/gemini-3.1-pro-preview","google/gemini-2.5-pro"],
  },
  "inference": {
    label: "Inference",
    client: "openai",
    baseURL: "https://inference.net/v1",
    envVar: "INFERENCE_API_KEY",
    models: ["google/gemma-3","qwen/qwen-2.5-7b-vision-instruct","qwen/qwen3-embedding-4b","meta/llama-3.2-1b-instruct","meta/llama-3.2-3b-instruct","meta/llama-3.1-8b-instruct","meta/llama-3.2-11b-vision-instruct","osmosis/osmosis-structure-0.6b"],
  },
  "evroc": {
    label: "evroc",
    client: "openai",
    baseURL: "https://models.think.evroc.com/v1",
    envVar: "EVROC_API_KEY",
    models: ["intfloat/multilingual-e5-large-instruct","nvidia/Llama-3.3-70B-Instruct-FP8","google/gemma-4-26B-A4B-it","zai-org/GLM-5.2","mistralai/Mistral-Medium-3.5-128B","mistralai/Voxtral-Small-24B-2507","evroc/roc","Qwen/Qwen3-Embedding-8B"],
  },
  "abacus": {
    label: "Abacus",
    client: "openai",
    baseURL: "https://routellm.abacus.ai/v1",
    envVar: "ABACUS_API_KEY",
    models: ["claude-sonnet-4-6","gpt-4.1-mini","gpt-4o","muse-spark-1.1","gemini-3.5-flash","gemini-2.5-flash","claude-3-7-sonnet-20250219","grok-4-0709"],
  },
  "inceptron": {
    label: "Inceptron",
    client: "openai",
    baseURL: "https://api.inceptron.io/v1",
    envVar: "INCEPTRON_API_KEY",
    models: ["zai-org/GLM-5.1-FP8","zai-org/GLM-5.2","MiniMaxAI/MiniMax-M2.5","moonshotai/Kimi-K2.6","moonshotai/Kimi-K2.6-Fast","moonshotai/Kimi-K2.7-Code"],
  },
  "empiriolabs": {
    label: "EmpirioLabs AI",
    client: "openai",
    baseURL: "https://api.empiriolabs.ai/v1",
    envVar: "EMPIRIOLABS_API_KEY",
    models: ["mimo-v2-5","minimax-m2-7-highspeed","qwen3-5-397b-a17b","glm-4-7-flash","qwen3-5-122b-a10b","kimi-k2-7-code-highspeed","qwen3-5-9b","kimi-k2-6"],
  },
  "alibaba-token-plan": {
    label: "Alibaba Token Plan",
    client: "openai",
    baseURL: "https://token-plan.ap-southeast-1.maas.aliyuncs.com/compatible-mode/v1",
    envVar: "ALIBABA_TOKEN_PLAN_API_KEY",
    models: ["qwen3.7-plus","qwen3.8-max-preview","glm-5","glm-5.1","deepseek-v4-flash","kimi-k2.5","glm-5.2","wan2.7-image-pro"],
  },
  "meta": {
    label: "Meta",
    client: "openai",
    baseURL: "https://api.meta.ai/v1",
    envVar: "META_MODEL_API_KEY",
    models: ["muse-spark-1.1"],
  },
  "wafer.ai": {
    label: "Wafer",
    client: "openai",
    baseURL: "https://pass.wafer.ai/v1",
    envVar: "WAFER_API_KEY",
    models: ["Kimi-K2.6","GLM-5.2","GLM-5.1","glm5.2-fast","MiniMax-M3"],
  },
  "clarifai": {
    label: "Clarifai",
    client: "openai",
    baseURL: "https://api.clarifai.com/v2/ext/openai/v1",
    envVar: "CLARIFAI_PAT",
    models: ["qwen/qwenCoder/models/Qwen3-Coder-30B-A3B-Instruct","qwen/qwenLM/models/Qwen3-30B-A3B-Thinking-2507","qwen/qwenLM/models/Qwen3-30B-A3B-Instruct-2507","mistralai/completion/models/Ministral-3-3B-Reasoning-2512","mistralai/completion/models/Ministral-3-14B-Reasoning-2512","clarifai/main/models/mm-poly-8b","deepseek-ai/deepseek-ocr/models/DeepSeek-OCR","arcee_ai/AFM/models/trinity-mini"],
  },
  "iflowcn": {
    label: "iFlow",
    client: "openai",
    baseURL: "https://apis.iflow.cn/v1",
    envVar: "IFLOW_API_KEY",
    models: ["qwen3-vl-plus","qwen3-32b","qwen3-235b-a22b-thinking-2507","qwen3-235b","qwen3-max-preview","qwen3-max","glm-4.6","qwen3-coder-plus"],
  },
  "bailing": {
    label: "Bailing",
    client: "openai",
    baseURL: "https://api.tbox.cn/api/llm/v1/chat/completions",
    envVar: "BAILING_API_TOKEN",
    models: ["Ling-1T","Ring-1T"],
  },
  "mixlayer": {
    label: "Mixlayer",
    client: "openai",
    baseURL: "https://models.mixlayer.ai/v1",
    envVar: "MIXLAYER_API_KEY",
    models: ["qwen/qwen3.5-27b","qwen/qwen3.5-9b","qwen/qwen3.5-35b-a3b","qwen/qwen3.5-397b-a17b","qwen/qwen3.5-122b-a10b"],
  },
  "scaleway": {
    label: "Scaleway",
    client: "openai",
    baseURL: "https://api.scaleway.ai/v1",
    envVar: "SCALEWAY_API_KEY",
    models: ["mistral-medium-3.5-128b","qwen3.6-35b-a3b","bge-multilingual-gemma2","qwen3-coder-30b-a3b-instruct","glm-5.2","devstral-2-123b-instruct-2512","pixtral-12b-2409","gemma-4-26b-a4b-it"],
  },
  "digitalocean": {
    label: "DigitalOcean",
    client: "openai",
    baseURL: "https://inference.do-ai.run/v1",
    envVar: "DIGITALOCEAN_ACCESS_TOKEN",
    models: ["anthropic-claude-opus-4.8","openai-gpt-image-1","anthropic-claude-3.5-sonnet","glm-5","openai-gpt-4.1","gte-large-en-v1.5","mistral-3-14B","openai-gpt-5.4-pro"],
  },
  "moonshotai-cn": {
    label: "Moonshot AI (China)",
    client: "openai",
    baseURL: "https://api.moonshot.cn/v1",
    envVar: "MOONSHOT_API_KEY",
    models: ["kimi-k3","kimi-k2-thinking","kimi-k2.7-code","kimi-k2-0905-preview","kimi-k2-turbo-preview","kimi-k2.6","kimi-k2.7-code-highspeed","kimi-k2-0711-preview"],
  },
  "model-oracle-ai": {
    label: "Model Oracle AI",
    client: "openai",
    baseURL: "https://api.modeloracle.com/api/v1",
    envVar: "MODEL_ORACLE_API_KEY",
    models: ["gpt-4.1-mini","claude-fable-5","glm-5.2","gpt-5.5","gpt-5","deepseek-v4-pro","gpt-5.4","gpt-5.4-nano"],
  },
  "drun": {
    label: "D.Run (China)",
    client: "openai",
    baseURL: "https://chat.d.run/v1",
    envVar: "DRUN_API_KEY",
    models: ["public/minimax-m25","public/deepseek-v3","public/deepseek-r1"],
  },
  "lmstudio": {
    label: "LMStudio",
    client: "openai",
    baseURL: "http://127.0.0.1:1234/v1",
    envVar: "LMSTUDIO_API_KEY",
    models: ["qwen/qwen3-coder-30b","qwen/qwen3-30b-a3b-2507","openai/gpt-oss-20b"],
  },
  "ovhcloud": {
    label: "OVHcloud AI Endpoints",
    client: "openai",
    baseURL: "https://oai.endpoints.kepler.ai.cloud.ovh.net/v1",
    envVar: "OVHCLOUD_API_KEY",
    models: ["qwen3-32b","qwen3-coder-30b-a3b-instruct","gpt-oss-20b","mistral-nemo-instruct-2407","meta-llama-3_3-70b-instruct","qwen3.5-9b","qwen3.6-27b","qwen3guard-gen-8b"],
  },
  "zeldoc": {
    label: "Zeldoc",
    client: "openai",
    baseURL: "https://api.zeldoc.ai/v1",
    envVar: "ZELDOC_API_KEY",
    models: ["z-code"],
  },
  "auriko": {
    label: "Auriko",
    client: "openai",
    baseURL: "https://api.auriko.ai/v1",
    envVar: "AURIKO_API_KEY",
    models: ["minimax-m2-7-highspeed","claude-sonnet-4-6","gemini-2.5-flash","glm-5.1","claude-opus-4-6","deepseek-v4-flash","kimi-k2.5","grok-4.3"],
  },
  "kuae-cloud-coding-plan": {
    label: "KUAE Cloud Coding Plan",
    client: "openai",
    baseURL: "https://coding-plan-endpoint.kuaecloud.net/v1",
    envVar: "KUAE_API_KEY",
    models: ["GLM-4.7"],
  },
  "qihang-ai": {
    label: "QiHang",
    client: "openai",
    baseURL: "https://api.qhaigc.net/v1",
    envVar: "QIHANG_API_KEY",
    models: ["gemini-2.5-flash","gemini-3-flash-preview","claude-sonnet-4-5-20250929","gpt-5.2-codex","claude-opus-4-5-20251101","gpt-5.2","gpt-5-mini","claude-haiku-4-5-20251001"],
  },
  "berget": {
    label: "Berget.AI",
    client: "openai",
    baseURL: "https://api.berget.ai/v1",
    envVar: "BERGET_API_KEY",
    models: ["google/gemma-4-31B-it","zai-org/GLM-5.2","zai-org/GLM-4.7","mistralai/Mistral-Medium-3.5-128B","mistralai/Mistral-Small-3.2-24B-Instruct-2506","moonshotai/Kimi-K2.6","openai/gpt-oss-120b","meta-llama/Llama-3.3-70B-Instruct"],
  },
  "moark": {
    label: "Moark",
    client: "openai",
    baseURL: "https://moark.com/v1",
    envVar: "MOARK_API_KEY",
    models: ["MiniMax-M2.1","GLM-4.7"],
  },
  "nova": {
    label: "Nova",
    client: "openai",
    baseURL: "https://api.nova.amazon.com/v1",
    envVar: "NOVA_API_KEY",
    models: ["nova-2-lite-v1","nova-2-pro-v1"],
  },
  "vultr": {
    label: "Vultr",
    client: "openai",
    baseURL: "https://api.vultrinference.com/v1",
    envVar: "VULTR_API_KEY",
    models: ["nvidia/Nemotron-3-Nano-Omni-30B-A3B-Reasoning-BF16","nvidia/DeepSeek-V3.2-NVFP4","nvidia/Nemotron-Cascade-2-30B-A3B","zai-org/GLM-5.2-FP8","Qwen/Qwen3.6-27B","Qwen/Qwen3.5-397B-A17B","MiniMaxAI/MiniMax-M2.7","deepseek-ai/DeepSeek-V4-Flash"],
  },
  "io-net": {
    label: "IO.NET",
    client: "openai",
    baseURL: "https://api.intelligence.io.solutions/api/v1",
    envVar: "IOINTELLIGENCE_API_KEY",
    models: ["zai-org/GLM-4.6","mistralai/Devstral-Small-2505","mistralai/Mistral-Large-Instruct-2411","mistralai/Mistral-Nemo-Instruct-2407","mistralai/Magistral-Small-2506","Qwen/Qwen2.5-VL-32B-Instruct","Qwen/Qwen3-Next-80B-A3B-Instruct","Qwen/Qwen3-235B-A22B-Thinking-2507"],
  },
  "neuralwatt": {
    label: "Neuralwatt",
    client: "openai",
    baseURL: "https://api.neuralwatt.com/v1",
    envVar: "NEURALWATT_API_KEY",
    models: ["glm-5.2-short-fast","glm-5.2-short","glm-5.2","glm-5.2-short-flex","kimi-k2.6-flex","kimi-k2.5-fast","qwen3.6-35b-fast","qwen3.5-397b-fast"],
  },
  "aki-io": {
    label: "AKI.IO",
    client: "openai",
    baseURL: "https://aki.io/v1",
    envVar: "AKI_IO_API_KEY",
    models: ["mistral4-119b","minimax-m2.5-230b","gpt-oss-120b","gemma4-26b","kimi-k2.7-code-1100b","qwen3.6-35b"],
  },
  "hetzner": {
    label: "Hetzner",
    client: "openai",
    baseURL: "https://inference.hetzner.com/api/v1",
    envVar: "HETZNER_API_KEY",
    models: ["Qwen/Qwen3.6-35B-A3B-FP8"],
  },
  "zenifra": {
    label: "Zenifra",
    client: "openai",
    baseURL: "https://ai.zenifra.com/v1",
    envVar: "ZENIFRA_AI_KEY",
    models: ["alibaba/qwen3.6-35b-a3b"],
  },
  "morph": {
    label: "Morph",
    client: "openai",
    baseURL: "https://api.morphllm.com/v1",
    envVar: "MORPH_API_KEY",
    models: ["morph-v3-large","auto","morph-v3-fast"],
  },
  "umans-ai-coding-plan": {
    label: "Umans AI Coding Plan",
    client: "openai",
    baseURL: "https://api.code.umans.ai/v1",
    envVar: "UMANS_AI_CODING_PLAN_API_KEY",
    models: ["umans-flash","umans-coder","umans-glm-5.2","umans-kimi-k2.7","umans-qwen3.6-35b-a3b","umans-glm-5.1"],
  },
  "umans-ai": {
    label: "Umans AI",
    client: "openai",
    baseURL: "https://api.code.umans.ai/v1",
    envVar: "UMANS_AI_API_KEY",
    models: ["umans-flash","umans-coder","umans-glm-5.2","umans-kimi-k2.7","umans-glm-5.1"],
  },
  "ofox": {
    label: "Ofox",
    client: "openai",
    baseURL: "https://api.ofox.ai/v1",
    envVar: "OFOX_API_KEY",
    models: ["google/gemini-3.1-pro-preview","deepseek/deepseek-v4-pro","x-ai/grok-4.3","anthropic/claude-fable-5","anthropic/claude-opus-4.8","anthropic/claude-sonnet-5","z-ai/glm-5.2","moonshotai/kimi-k2.6"],
  },
  "orcarouter": {
    label: "OrcaRouter",
    client: "openai",
    baseURL: "https://api.orcarouter.ai/v1",
    envVar: "ORCAROUTER_API_KEY",
    models: ["google/gemini-flash-latest","google/gemini-2.5-flash","google/gemini-3.1-flash-lite-preview","google/gemini-3-flash-preview","google/gemini-3.1-pro-preview-customtools","google/gemma-4-26b-a4b-it","google/gemma-4-31b-it","google/gemini-3.1-pro-preview"],
  },
  "xiaomi-token-plan-cn": {
    label: "Xiaomi Token Plan (China)",
    client: "openai",
    baseURL: "https://token-plan-cn.xiaomimimo.com/v1",
    envVar: "XIAOMI_API_KEY",
    models: ["mimo-v2.5-tts","mimo-v2-tts","mimo-v2-pro","mimo-v2.5-tts-voicedesign","mimo-v2.5","mimo-v2.5-tts-voiceclone","mimo-v2.5-pro"],
  },
  "poolside": {
    label: "Poolside",
    client: "openai",
    baseURL: "https://inference.poolside.ai/v1",
    envVar: "POOLSIDE_API_KEY",
    models: ["poolside/laguna-xs-2.1","poolside/laguna-s-2.1","poolside/laguna-m.1"],
  },
  "routing-run": {
    label: "routing.run",
    client: "openai",
    baseURL: "https://api.routing.run/v1",
    envVar: "ROUTING_RUN_API_KEY",
    models: ["claude-sonnet-4-6","gpt-5.6-sol","deepseek-v4-flash","claude-opus-4-8","glm-5.2","qwen3.5-9b","nemotron-3-ultra","kimi-k2.6"],
  },
  "tencent-token-plan": {
    label: "Tencent Token Plan",
    client: "openai",
    baseURL: "https://api.lkeap.cloud.tencent.com/plan/v3",
    envVar: "TENCENT_TOKEN_PLAN_API_KEY",
    models: ["hy3"],
  },
  "synthetic": {
    label: "Synthetic",
    client: "openai",
    baseURL: "https://api.synthetic.new/openai/v1",
    envVar: "SYNTHETIC_API_KEY",
    models: ["hf:Qwen/Qwen3.6-27B","hf:nvidia/NVIDIA-Nemotron-3-Super-120B-A12B-NVFP4","hf:moonshotai/Kimi-K2.7-Code","hf:moonshotai/Kimi-K3","hf:openai/gpt-oss-120b","hf:zai-org/GLM-4.7-Flash","hf:zai-org/GLM-5.2","hf:MiniMaxAI/MiniMax-M3"],
  },
  "zai-coding-plan": {
    label: "Z.AI Coding Plan",
    client: "openai",
    baseURL: "https://api.z.ai/api/coding/paas/v4",
    envVar: "ZHIPU_API_KEY",
    models: ["glm-4.5-air","glm-5.1","glm-5.2","glm-4.7","glm-5-turbo","glm-5v-turbo"],
  },
  "gmicloud": {
    label: "GMI Cloud",
    client: "openai",
    baseURL: "https://api.gmi-serving.com/v1",
    envVar: "GMICLOUD_API_KEY",
    models: ["zai-org/GLM-5.1-FP8","zai-org/GLM-5-FP8","zai-org/GLM-5.2-FP8","Qwen/Qwen3.7-Max","deepseek-ai/DeepSeek-V4-Flash","deepseek-ai/DeepSeek-V4-Pro","anthropic/claude-sonnet-4.6","anthropic/claude-opus-4.7"],
  },
  "freemodel": {
    label: "FreeModel",
    client: "anthropic",
    baseURL: "https://cc.freemodel.dev/v1",
    envVar: "FREEMODEL_API_KEY",
    models: ["claude-sonnet-4-6","claude-opus-4-6","claude-fable-5","claude-opus-4-8","gpt-5.5","gpt-5.4","gpt-5.4-mini","gpt-5.3-codex"],
  },
  "xiaomi-token-plan-ams": {
    label: "Xiaomi Token Plan (Europe)",
    client: "openai",
    baseURL: "https://token-plan-ams.xiaomimimo.com/v1",
    envVar: "XIAOMI_API_KEY",
    models: ["mimo-v2.5-pro","mimo-v2.5-tts-voiceclone","mimo-v2.5","mimo-v2.5-tts-voicedesign","mimo-v2-pro","mimo-v2-tts","mimo-v2.5-tts"],
  },
  "minimax": {
    label: "MiniMax (minimax.io)",
    client: "anthropic",
    baseURL: "https://api.minimax.io/anthropic/v1",
    envVar: "MINIMAX_API_KEY",
    models: ["MiniMax-M2","MiniMax-M2.7","MiniMax-M2.1","MiniMax-M2.5","MiniMax-M2.5-highspeed","MiniMax-M2.7-highspeed","MiniMax-M3"],
  },
  "deepseek": {
    label: "DeepSeek",
    client: "openai",
    baseURL: "https://api.deepseek.com",
    envVar: "DEEPSEEK_API_KEY",
    models: ["deepseek-v4-flash","deepseek-v4-pro","deepseek-chat","deepseek-reasoner"],
  },
  "kimi-for-coding": {
    label: "Kimi For Coding",
    client: "anthropic",
    baseURL: "https://api.kimi.com/coding/v1",
    envVar: "KIMI_API_KEY",
    models: ["k3","kimi-for-coding","kimi-for-coding-highspeed","k3-256k"],
  },
  "requesty": {
    label: "Requesty",
    client: "openai",
    baseURL: "https://router.requesty.ai/v1",
    envVar: "REQUESTY_API_KEY",
    models: ["google/gemini-2.5-flash","google/gemini-3-flash-preview","google/gemini-2.5-pro","google/gemini-3-pro-preview","xai/grok-4","xai/grok-4-fast","anthropic/claude-sonnet-4-6","anthropic/claude-haiku-4-5"],
  },
  "llama": {
    label: "Llama",
    client: "openai",
    baseURL: "https://api.llama.com/compat/v1/",
    envVar: "LLAMA_API_KEY",
    models: ["cerebras-llama-4-maverick-17b-128e-instruct","cerebras-llama-4-scout-17b-16e-instruct","llama-4-scout-17b-16e-instruct-fp8","llama-4-maverick-17b-128e-instruct-fp8","llama-3.3-70b-instruct","llama-3.3-8b-instruct","groq-llama-4-maverick-17b-128e-instruct"],
  },
  "kilo": {
    label: "Kilo Gateway",
    client: "openai",
    baseURL: "https://api.kilo.ai/api/gateway",
    envVar: "KILO_API_KEY",
    models: ["~openai/gpt-latest","~openai/gpt-mini-latest","microsoft/phi-4-mini-instruct","microsoft/phi-4","microsoft/wizardlm-2-8x22b","cohere/command-r-08-2024","cohere/command-a","cohere/command-r-plus-08-2024"],
  },
  "cloudferro-sherlock": {
    label: "CloudFerro Sherlock",
    client: "openai",
    baseURL: "https://api-sherlock.cloudferro.com/openai/v1/",
    envVar: "CLOUDFERRO_SHERLOCK_API_KEY",
    models: ["MiniMaxAI/MiniMax-M2.5","speakleash/Bielik-11B-v3.0-Instruct","speakleash/Bielik-11B-v2.6-Instruct","openai/gpt-oss-120b","meta-llama/Llama-3.3-70B-Instruct"],
  },
  "subconscious": {
    label: "Subconscious",
    client: "anthropic",
    baseURL: "https://api.subconscious.dev/v1",
    envVar: "SUBCONSCIOUS_API_KEY",
    models: ["subconscious/glm-5.2","subconscious/tim-qwen3.6-27b"],
  },
  "tencent-coding-plan": {
    label: "Tencent Coding Plan (China)",
    client: "openai",
    baseURL: "https://api.lkeap.cloud.tencent.com/coding/v3",
    envVar: "TENCENT_CODING_PLAN_API_KEY",
    models: ["glm-5","kimi-k2.5","hunyuan-2.0-instruct","hunyuan-2.0-thinking","hunyuan-turbos","minimax-m2.5","hunyuan-t1","tc-code-latest"],
  },
  "hyper": {
    label: "Charm Hyper",
    client: "openai",
    baseURL: "https://hyper.charm.land/v1",
    envVar: "HYPER_API_KEY",
    models: ["qwen3.7-plus","glm-5","glm-5.1","deepseek-v4-flash","kimi-k2.5","minimax-m2.7","glm-5.2","qwen3.7-max"],
  },
  "alibaba": {
    label: "Alibaba",
    client: "openai",
    baseURL: "https://dashscope-intl.aliyuncs.com/compatible-mode/v1",
    envVar: "DASHSCOPE_API_KEY",
    models: ["qwen3-coder-480b-a35b-instruct","qwen3.7-plus","qwen3-vl-plus","qwen3-32b","qwen3.6-35b-a3b","qwen-mt-plus","qwen2-5-vl-72b-instruct","qwen-max"],
  },
  "github-models": {
    label: "GitHub Models",
    client: "openai",
    baseURL: "https://models.github.ai/inference",
    envVar: "GITHUB_TOKEN",
    models: ["microsoft/phi-3.5-vision-instruct","microsoft/phi-4-mini-instruct","microsoft/phi-3.5-mini-instruct","microsoft/phi-3-medium-4k-instruct","microsoft/phi-4","microsoft/phi-4-reasoning","microsoft/phi-3.5-moe-instruct","microsoft/phi-3-mini-4k-instruct"],
  },
  "alibaba-cn": {
    label: "Alibaba (China)",
    client: "openai",
    baseURL: "https://dashscope.aliyuncs.com/compatible-mode/v1",
    envVar: "DASHSCOPE_API_KEY",
    models: ["qwen3-coder-480b-a35b-instruct","qwen3.7-plus","qwen3-vl-plus","qwen3-32b","glm-5","qwen-mt-plus","qwen2-5-vl-72b-instruct","qwen-max"],
  },
  "novita-ai": {
    label: "NovitaAI",
    client: "openai",
    baseURL: "https://api.novita.ai/openai",
    envVar: "NOVITA_API_KEY",
    models: ["microsoft/wizardlm-2-8x22b","google/gemma-4-26b-a4b-it","google/gemma-3-27b-it","google/gemma-3-12b-it","google/gemma-4-31b-it","zai-org/glm-4.6v","zai-org/glm-5","zai-org/glm-4.5-air"],
  },
  "openrouter": {
    label: "OpenRouter",
    client: "openai",
    baseURL: "https://openrouter.ai/api/v1",
    envVar: "OPENROUTER_API_KEY",
    models: ["~openai/gpt-latest","~openai/gpt-mini-latest","microsoft/phi-4","microsoft/wizardlm-2-8x22b","cohere/command-r-08-2024","cohere/command-a","cohere/command-r-plus-08-2024","cohere/command-r7b-12-2024"],
  },
  "huggingface": {
    label: "Hugging Face",
    client: "openai",
    baseURL: "https://router.huggingface.co/v1",
    envVar: "HF_TOKEN",
    models: ["google/gemma-4-26B-A4B-it","google/gemma-4-31B-it","zai-org/GLM-5","zai-org/GLM-4.5","zai-org/GLM-4.5-Air","zai-org/GLM-4.5V","zai-org/GLM-4.7-Flash","zai-org/GLM-5.2"],
  },
  "minimax-coding-plan": {
    label: "MiniMax Token Plan (minimax.io)",
    client: "anthropic",
    baseURL: "https://api.minimax.io/anthropic/v1",
    envVar: "MINIMAX_API_KEY",
    models: ["MiniMax-M2","MiniMax-M2.7","MiniMax-M2.1","MiniMax-M2.5","MiniMax-M2.5-highspeed","MiniMax-M2.7-highspeed","MiniMax-M3"],
  },
  "siliconflow-cn": {
    label: "SiliconFlow (China)",
    client: "openai",
    baseURL: "https://api.siliconflow.cn/v1",
    envVar: "SILICONFLOW_CN_API_KEY",
    models: ["zai-org/GLM-5.2","zai-org/GLM-4.5-Air","PaddlePaddle/PaddleOCR-VL-1.5","tencent/Hunyuan-A13B-Instruct","Pro/zai-org/GLM-5","Pro/zai-org/GLM-5.1","Pro/MiniMaxAI/MiniMax-M2.5","Pro/deepseek-ai/DeepSeek-V3"],
  },
  "tinfoil": {
    label: "Tinfoil",
    client: "openai",
    baseURL: "https://inference.tinfoil.sh/v1",
    envVar: "TINFOIL_API_KEY",
    models: ["gemma4-31b","kimi-k2-6","gpt-oss-safeguard-120b","llama3-3-70b","glm-5-2","nomic-embed-text","gpt-oss-120b"],
  },
  "xiaomi": {
    label: "Xiaomi",
    client: "openai",
    baseURL: "https://api.xiaomimimo.com/v1",
    envVar: "XIAOMI_API_KEY",
    models: ["mimo-v2-omni","mimo-v2-flash","mimo-v2.5-pro-ultraspeed","mimo-v2-pro","mimo-v2.5","mimo-v2.5-pro"],
  },
  "stackit": {
    label: "STACKIT",
    client: "openai",
    baseURL: "https://api.openai-compat.model-serving.eu01.onstackit.cloud/v1",
    envVar: "STACKIT_API_KEY",
    models: ["intfloat/e5-mistral-7b-instruct","google/gemma-3-27b-it","Qwen/Qwen3-VL-Embedding-8B","Qwen/Qwen3.6-27B","Qwen/Qwen3-VL-235B-A22B-Instruct-FP8","openai/gpt-oss-20b","openai/gpt-oss-120b","cortecs/Llama-3.3-70B-Instruct-FP8-Dynamic"],
  },
  "lynkr": {
    label: "Lynkr",
    client: "openai",
    baseURL: "http://127.0.0.1:8081/v1",
    envVar: "LYNKR_API_KEY",
    models: ["lynkr-auto"],
  },
  "alibaba-token-plan-cn": {
    label: "Alibaba Token Plan (China)",
    client: "openai",
    baseURL: "https://token-plan.cn-beijing.maas.aliyuncs.com/compatible-mode/v1",
    envVar: "ALIBABA_TOKEN_PLAN_API_KEY",
    models: ["qwen3.7-plus","qwen3.8-max-preview","glm-5","glm-5.1","deepseek-v4-flash","kimi-k2.5","glm-5.2","wan2.7-image-pro"],
  },
  "stepfun-ai": {
    label: "StepFun (Global)",
    client: "openai",
    baseURL: "https://api.stepfun.ai/v1",
    envVar: "STEPFUN_API_KEY",
    models: ["step-2-16k","stepaudio-2.5-asr","step-1-32k","stepaudio-2.5-tts","step-tts-2","step-3.5-flash-2603","step-3.7-flash","step-3.5-flash"],
  },
  "chutes": {
    label: "Chutes",
    client: "openai",
    baseURL: "https://llm.chutes.ai/v1",
    envVar: "CHUTES_API_KEY",
    models: ["Nemotron-3-Nano-Omni-30B-TEE","google/gemma-4-31B-turbo-TEE","zai-org/GLM-5-TEE","zai-org/GLM-5.1-TEE","zai-org/GLM-5.2-TEE","unsloth/Mistral-Nemo-Instruct-2407-TEE","Qwen/Qwen3-235B-A22B-Thinking-2507-TEE","Qwen/Qwen3-32B-TEE"],
  },
  "qiniu-ai": {
    label: "Qiniu",
    client: "openai",
    baseURL: "https://api.qnaigc.com/v1",
    envVar: "QINIU_API_KEY",
    models: ["qwen3-coder-480b-a35b-instruct","qwen-vl-max-2025-01-25","qwen3-32b","deepseek-v3.1","doubao-1.5-vision-pro","claude-3.7-sonnet","qwen3-30b-a3b","glm-4.5-air"],
  },
  "longcat": {
    label: "LongCat",
    client: "openai",
    baseURL: "https://api.longcat.chat/openai",
    envVar: "LONGCAT_API_KEY",
    models: ["LongCat-2.0"],
  },
  "ollama-cloud": {
    label: "Ollama Cloud",
    client: "openai",
    baseURL: "https://ollama.com/v1",
    envVar: "OLLAMA_API_KEY",
    models: ["glm-5.1","nemotron-3-super","deepseek-v4-flash","kimi-k2.5","minimax-m2.7","nemotron-3-nano:30b","mistral-large-3:675b","glm-5.2"],
  },
  "jiekou": {
    label: "Jiekou.AI",
    client: "openai",
    baseURL: "https://api.jiekou.ai/openai",
    envVar: "JIEKOU_API_KEY",
    models: ["gpt-5.1-codex-mini","gpt-5.2-pro","gemini-2.5-flash-lite-preview-06-17","grok-4-fast-reasoning","gemini-2.5-flash","grok-4-0709","claude-opus-4-6","o3-mini"],
  },
  "perplexity-agent": {
    label: "Perplexity Agent",
    client: "openai",
    baseURL: "https://api.perplexity.ai/v1",
    envVar: "PERPLEXITY_API_KEY",
    models: ["nvidia/nemotron-3-super-120b-a12b","google/gemini-2.5-flash","google/gemini-3-flash-preview","google/gemini-3.1-pro-preview","google/gemini-2.5-pro","xai/grok-4-1-fast-non-reasoning","anthropic/claude-sonnet-4-6","anthropic/claude-haiku-4-5"],
  },
  "moonshotai": {
    label: "Moonshot AI",
    client: "openai",
    baseURL: "https://api.moonshot.ai/v1",
    envVar: "MOONSHOT_API_KEY",
    models: ["kimi-k2.5","kimi-k2-thinking-turbo","kimi-k2-0711-preview","kimi-k2.7-code-highspeed","kimi-k2.6","kimi-k2-turbo-preview","kimi-k2-0905-preview","kimi-k2.7-code"],
  },
  "xpersona": {
    label: "Xpersona",
    client: "openai",
    baseURL: "https://www.xpersona.co/v1",
    envVar: "XPERSONA_API_KEY",
    models: ["xpersona-frieren-coder","claude-fable-5","xpersona-gpt-5.5"],
  },
  "sarvam": {
    label: "Sarvam AI",
    client: "openai",
    baseURL: "https://api.sarvam.ai/v1",
    envVar: "SARVAM_API_KEY",
    models: ["sarvam-30b","sarvam-105b"],
  },
  "zai": {
    label: "Z.AI",
    client: "openai",
    baseURL: "https://api.z.ai/api/paas/v4",
    envVar: "ZHIPU_API_KEY",
    models: ["glm-4.6v","glm-5","glm-4.5-air","glm-5.1","glm-4.7-flash","glm-5.2","glm-4.7-flashx","glm-4.6"],
  },
  "inferx": {
    label: "InferX",
    client: "openai",
    baseURL: "https://model.inferx.net/endpoints/v1",
    envVar: "INFERX_API_KEY",
    models: ["qwen3-coder-next-fp8-1m","qwen3-coder-next-fp8","google/gemma-4-31b-it-fp8","qwen/qwen3.6-35b-a3b-fp8","qwen/qwen3.5-122b-a10b-nvfp4","qwen/qwen3.6-27b-fp8"],
  },
  "meganova": {
    label: "Meganova",
    client: "openai",
    baseURL: "https://api.meganova.ai/v1",
    envVar: "MEGANOVA_API_KEY",
    models: ["zai-org/GLM-5","zai-org/GLM-4.6","zai-org/GLM-4.7","mistralai/Mistral-Nemo-Instruct-2407","mistralai/Mistral-Small-3.2-24B-Instruct-2506","Qwen/Qwen3-235B-A22B-Instruct-2507","Qwen/Qwen2.5-VL-32B-Instruct","Qwen/Qwen3.5-Plus"],
  },
  "stepfun": {
    label: "StepFun (China)",
    client: "openai",
    baseURL: "https://api.stepfun.com/v1",
    envVar: "STEPFUN_API_KEY",
    models: ["step-3.5-flash","step-3.7-flash","step-3.5-flash-2603","step-tts-2","stepaudio-2.5-tts","step-1-32k","stepaudio-2.5-asr","step-2-16k"],
  },
  "cortecs": {
    label: "Cortecs",
    client: "openai",
    baseURL: "https://api.cortecs.ai/v1",
    envVar: "CORTECS_API_KEY",
    models: ["qwen3-coder-480b-a35b-instruct","claude-opus4-7","qwen3-32b","glm-5","claude-4-6-sonnet","claude-haiku-4-5","glm-4.5-air","glm-5.1"],
  },
  "xiaomi-token-plan-sgp": {
    label: "Xiaomi Token Plan (Singapore)",
    client: "openai",
    baseURL: "https://token-plan-sgp.xiaomimimo.com/v1",
    envVar: "XIAOMI_API_KEY",
    models: ["mimo-v2.5-pro","mimo-v2.5-tts-voiceclone","mimo-v2.5","mimo-v2.5-tts-voicedesign","mimo-v2-pro","mimo-v2-tts","mimo-v2.5-tts"],
  },
  "hpc-ai": {
    label: "HPC-AI",
    client: "openai",
    baseURL: "https://api.hpc-ai.com/inference/v1",
    envVar: "HPC_AI_API_KEY",
    models: ["zai-org/glm-5.1","zai-org/glm-5.2","minimax/minimax-m2.5","deepseek/deepseek-v4-flash","deepseek/deepseek-v4-pro","anthropic/claude-opus-4.7","moonshotai/kimi-k2.5","moonshotai/kimi-k2.7-code"],
  },
  "minimax-cn": {
    label: "MiniMax (minimaxi.com)",
    client: "anthropic",
    baseURL: "https://api.minimaxi.com/anthropic/v1",
    envVar: "MINIMAX_API_KEY",
    models: ["MiniMax-M2","MiniMax-M2.7","MiniMax-M2.1","MiniMax-M2.5","MiniMax-M2.5-highspeed","MiniMax-M2.7-highspeed","MiniMax-M3"],
  },
  "ebcloud": {
    label: "EBCloud",
    client: "openai",
    baseURL: "https://maas-api.ebcloud.com/v1",
    envVar: "EBCLOUD_API_KEY",
    models: ["Kimi-K2.6","DeepSeek-V4-Flash","GLM-5.1","DeepSeek-V4-Pro"],
  },
  "databricks": {
    label: "Databricks",
    client: "openai",
    baseURL: "https://${DATABRICKS_HOST}/ai-gateway/mlflow/v1",
    envVar: "DATABRICKS_HOST",
    models: ["databricks-gpt-5-nano","databricks-gemini-3-1-flash-lite","databricks-gpt-oss-120b","databricks-claude-opus-4-5","databricks-claude-sonnet-4-6","databricks-claude-sonnet-4","databricks-gemini-3-flash","databricks-gpt-oss-20b"],
  },
  "minimax-cn-coding-plan": {
    label: "MiniMax Token Plan (minimaxi.com)",
    client: "anthropic",
    baseURL: "https://api.minimaxi.com/anthropic/v1",
    envVar: "MINIMAX_API_KEY",
    models: ["MiniMax-M2","MiniMax-M2.7","MiniMax-M2.1","MiniMax-M2.5","MiniMax-M2.5-highspeed","MiniMax-M2.7-highspeed","MiniMax-M3"],
  },
};
