// GENERATED — do not hand-edit. Regenerate with: bun run gen:catalog
// Source: https://models.dev/api.json (the same provider registry opencode uses), filtered to ALLOW_IDS.
// 16 providers included, 162 skipped (unlisted, need a dedicated SDK/auth flow, or missing an env var/base URL/model list).
import type { CatalogEntry } from "./catalog.ts";

export const GENERATED_CATALOG: Record<string, CatalogEntry> = {
  "baseten": {
    label: "Baseten",
    client: "openai",
    baseURL: "https://inference.baseten.co/v1",
    envVar: "BASETEN_API_KEY",
    models: ["nvidia/Nemotron-120B-A12B","nvidia/NVIDIA-Nemotron-3-Ultra-550B-A55B","thinkingmachines/inkling-small","thinkingmachines/inkling","zai-org/GLM-5","zai-org/GLM-5.2-Fast","zai-org/GLM-5.2","zai-org/GLM-5.1"],
  },
  "nvidia": {
    label: "Nvidia",
    client: "openai",
    baseURL: "https://integrate.api.nvidia.com/v1",
    envVar: "NVIDIA_API_KEY",
    models: ["microsoft/phi-4-mini-instruct","nvidia/cosmos-reason2-8b","nvidia/nemotron-nano-12b-v2-vl","nvidia/nemotron-3-nano-30b-a3b","nvidia/llama-3.3-nemotron-super-49b-v1.5","nvidia/llama-3.1-nemotron-nano-8b-v1","nvidia/llama-3.3-nemotron-super-49b-v1","nvidia/llama-3.1-nemotron-70b-instruct"],
  },
  "siliconflow": {
    label: "SiliconFlow",
    client: "openai",
    baseURL: "https://api.siliconflow.com/v1",
    envVar: "SILICONFLOW_API_KEY",
    models: ["google/gemma-4-26B-A4B-it","google/gemma-4-31B-it","zai-org/GLM-5","zai-org/GLM-4.5-Air","zai-org/GLM-5.2","zai-org/GLM-5.1","zai-org/GLM-5V-Turbo","tencent/Hunyuan-A13B-Instruct"],
  },
  "scaleway": {
    label: "Scaleway",
    client: "openai",
    baseURL: "https://api.scaleway.ai/v1",
    envVar: "SCALEWAY_API_KEY",
    models: ["mistral-medium-3.5-128b","qwen3.6-35b-a3b","qwen3-coder-30b-a3b-instruct","glm-5.2","pixtral-12b-2409","gemma-4-26b-a4b-it","llama-3.3-70b-instruct","qwen3-235b-a22b-instruct-2507"],
  },
  "digitalocean": {
    label: "DigitalOcean",
    client: "openai",
    baseURL: "https://inference.do-ai.run/v1",
    envVar: "DIGITALOCEAN_ACCESS_TOKEN",
    models: ["anthropic-claude-opus-4.8","anthropic-claude-3.5-sonnet","openai-gpt-5.6-terra","glm-5","openai-gpt-4.1","anthropic-claude-opus-5","mistral-3-14B","openai-gpt-5.4-pro"],
  },
  "lmstudio": {
    label: "LMStudio",
    client: "openai",
    baseURL: "http://127.0.0.1:1234/v1",
    envVar: "LMSTUDIO_API_KEY",
    models: ["qwen/qwen3-coder-30b","qwen/qwen3-30b-a3b-2507","openai/gpt-oss-20b"],
  },
  "minimax": {
    label: "MiniMax (minimax.io)",
    client: "anthropic",
    baseURL: "https://api.minimax.io/anthropic/v1",
    envVar: "MINIMAX_API_KEY",
    models: ["MiniMax-M2","MiniMax-M2.7","MiniMax-M2.1","MiniMax-M2.5","MiniMax-M2.5-highspeed","MiniMax-M2.7-highspeed","MiniMax-M3"],
  },
  "deepseek": {
    label: "DeepSeek",
    client: "openai",
    baseURL: "https://api.deepseek.com",
    envVar: "DEEPSEEK_API_KEY",
    models: ["deepseek-v4-flash","deepseek-v4-pro","deepseek-chat","deepseek-reasoner"],
  },
  "requesty": {
    label: "Requesty",
    client: "openai",
    baseURL: "https://router.requesty.ai/v1",
    envVar: "REQUESTY_API_KEY",
    models: ["claude-sonnet-4-6","claude-opus-5@eu","deepseek-v4-flash-0731@eu","gemini-3.5-flash@eu","claude-sonnet-4-6@eu","gpt-4.1-mini@eu","claude-haiku-4-5","claude-opus-4-7@eu"],
  },
  "alibaba": {
    label: "Alibaba",
    client: "openai",
    baseURL: "https://dashscope-intl.aliyuncs.com/compatible-mode/v1",
    envVar: "DASHSCOPE_API_KEY",
    models: ["qwen3-coder-480b-a35b-instruct","qwen3.7-plus","qwen3-vl-plus","qwen3-32b","qwen3.6-35b-a3b","qwen2-5-vl-72b-instruct","qwen-max","qwen3.5-plus"],
  },
  "novita-ai": {
    label: "NovitaAI",
    client: "openai",
    baseURL: "https://api.novita.ai/openai",
    envVar: "NOVITA_API_KEY",
    models: ["google/gemma-4-26b-a4b-it","google/gemma-4-31b-it","zai-org/glm-4.6v","zai-org/glm-5","zai-org/glm-4.5-air","zai-org/glm-5.1","zai-org/glm-4.7-flash","zai-org/glm-5.2"],
  },
  "openrouter": {
    label: "OpenRouter",
    client: "openai",
    baseURL: "https://openrouter.ai/api/v1",
    envVar: "OPENROUTER_API_KEY",
    models: ["~openai/gpt-latest","~openai/gpt-mini-latest","cohere/command-r-08-2024","cohere/command-r-plus-08-2024","cohere/north-mini-code:free","nvidia/nemotron-3-ultra-550b-a55b:free","nvidia/nemotron-3-nano-30b-a3b","nvidia/nemotron-nano-9b-v2:free"],
  },
  "huggingface": {
    label: "Hugging Face",
    client: "openai",
    baseURL: "https://router.huggingface.co/v1",
    envVar: "HF_TOKEN",
    models: ["google/gemma-4-26B-A4B-it","google/gemma-4-31B-it","thinkingmachines/Inkling-Small","thinkingmachines/Inkling","zai-org/GLM-5","zai-org/GLM-4.5","zai-org/GLM-4.5-Air","zai-org/GLM-4.5V"],
  },
  "ollama-cloud": {
    label: "Ollama Cloud",
    client: "openai",
    baseURL: "https://ollama.com/v1",
    envVar: "OLLAMA_API_KEY",
    models: ["glm-5.1","nemotron-3-super","deepseek-v4-flash","kimi-k2.5","minimax-m2.7","nemotron-3-nano:30b","mistral-large-3:675b","glm-5.2"],
  },
  "perplexity-agent": {
    label: "Perplexity Agent",
    client: "openai",
    baseURL: "https://api.perplexity.ai/v1",
    envVar: "PERPLEXITY_API_KEY",
    models: ["nvidia/nemotron-3-super-120b-a12b","google/gemini-2.5-flash","google/gemini-3-flash-preview","google/gemini-3.1-pro-preview","google/gemini-2.5-pro","moonshot-ai/kimi-k2.7-code","moonshot-ai/kimi-k3","xai/grok-4-1-fast-non-reasoning"],
  },
  "zai": {
    label: "Z.AI",
    client: "openai",
    baseURL: "https://api.z.ai/api/paas/v4",
    envVar: "ZHIPU_API_KEY",
    models: ["glm-4.6v","glm-5","glm-4.5-air","glm-5.1","glm-4.7-flash","glm-5.2","glm-4.7-flashx","glm-4.6"],
  },
};

// Exact "provider/model" → USD per 1M tokens, straight from models.dev. pricing.ts consults this
// before its hand-maintained prefix table.
export const GENERATED_PRICES: Record<string, { input: number; output: number }> = {
  "baseten/nvidia/Nemotron-120B-A12B": { input: 0.3, output: 0.75 },
  "baseten/nvidia/NVIDIA-Nemotron-3-Ultra-550B-A55B": { input: 0.6, output: 2.4 },
  "baseten/thinkingmachines/inkling-small": { input: 0.5, output: 1.2 },
  "baseten/thinkingmachines/inkling": { input: 1, output: 4.05 },
  "baseten/zai-org/GLM-5": { input: 0.95, output: 3.15 },
  "baseten/zai-org/GLM-5.2-Fast": { input: 2.1, output: 6.6 },
  "baseten/zai-org/GLM-5.2": { input: 1.4, output: 4.4 },
  "baseten/zai-org/GLM-5.1": { input: 1.3, output: 4.3 },
  "nvidia/microsoft/phi-4-mini-instruct": { input: 0, output: 0 },
  "nvidia/nvidia/cosmos-reason2-8b": { input: 0, output: 0 },
  "nvidia/nvidia/nemotron-nano-12b-v2-vl": { input: 0, output: 0 },
  "nvidia/nvidia/nemotron-3-nano-30b-a3b": { input: 0, output: 0 },
  "nvidia/nvidia/llama-3.3-nemotron-super-49b-v1.5": { input: 0, output: 0 },
  "nvidia/nvidia/llama-3.1-nemotron-nano-8b-v1": { input: 0, output: 0 },
  "nvidia/nvidia/llama-3.3-nemotron-super-49b-v1": { input: 0, output: 0 },
  "nvidia/nvidia/llama-3.1-nemotron-70b-instruct": { input: 0, output: 0 },
  "siliconflow/google/gemma-4-26B-A4B-it": { input: 0.12, output: 0.4 },
  "siliconflow/google/gemma-4-31B-it": { input: 0.13, output: 0.4 },
  "siliconflow/zai-org/GLM-5": { input: 0.95, output: 2.55 },
  "siliconflow/zai-org/GLM-4.5-Air": { input: 0.14, output: 0.86 },
  "siliconflow/zai-org/GLM-5.2": { input: 1.4, output: 4.4 },
  "siliconflow/zai-org/GLM-5.1": { input: 1.4, output: 4.4 },
  "siliconflow/zai-org/GLM-5V-Turbo": { input: 1.2, output: 4 },
  "siliconflow/tencent/Hunyuan-A13B-Instruct": { input: 0.14, output: 0.57 },
  "scaleway/mistral-medium-3.5-128b": { input: 1.5, output: 7.5 },
  "scaleway/qwen3.6-35b-a3b": { input: 0.25, output: 1.5 },
  "scaleway/qwen3-coder-30b-a3b-instruct": { input: 0.2, output: 0.8 },
  "scaleway/glm-5.2": { input: 1.8, output: 5.5 },
  "scaleway/pixtral-12b-2409": { input: 0.2, output: 0.2 },
  "scaleway/gemma-4-26b-a4b-it": { input: 0.25, output: 0.5 },
  "scaleway/llama-3.3-70b-instruct": { input: 0.9, output: 0.9 },
  "scaleway/qwen3-235b-a22b-instruct-2507": { input: 0.75, output: 2.25 },
  "digitalocean/anthropic-claude-opus-4.8": { input: 5, output: 25 },
  "digitalocean/anthropic-claude-3.5-sonnet": { input: 3, output: 15 },
  "digitalocean/openai-gpt-5.6-terra": { input: 2, output: 12 },
  "digitalocean/glm-5": { input: 0.75, output: 2.4 },
  "digitalocean/openai-gpt-4.1": { input: 2, output: 8 },
  "digitalocean/anthropic-claude-opus-5": { input: 5, output: 25 },
  "digitalocean/mistral-3-14B": { input: 0.2, output: 0.2 },
  "digitalocean/openai-gpt-5.4-pro": { input: 30, output: 180 },
  "lmstudio/qwen/qwen3-coder-30b": { input: 0, output: 0 },
  "lmstudio/qwen/qwen3-30b-a3b-2507": { input: 0, output: 0 },
  "lmstudio/openai/gpt-oss-20b": { input: 0, output: 0 },
  "minimax/MiniMax-M2": { input: 0.3, output: 1.2 },
  "minimax/MiniMax-M2.7": { input: 0.3, output: 1.2 },
  "minimax/MiniMax-M2.1": { input: 0.3, output: 1.2 },
  "minimax/MiniMax-M2.5": { input: 0.3, output: 1.2 },
  "minimax/MiniMax-M2.5-highspeed": { input: 0.6, output: 2.4 },
  "minimax/MiniMax-M2.7-highspeed": { input: 0.6, output: 2.4 },
  "minimax/MiniMax-M3": { input: 0.3, output: 1.2 },
  "deepseek/deepseek-v4-flash": { input: 0.14, output: 0.28 },
  "deepseek/deepseek-v4-pro": { input: 0.435, output: 0.87 },
  "deepseek/deepseek-chat": { input: 0.14, output: 0.28 },
  "deepseek/deepseek-reasoner": { input: 0.14, output: 0.28 },
  "requesty/claude-sonnet-4-6": { input: 3, output: 15 },
  "requesty/claude-opus-5@eu": { input: 5.5, output: 27.5 },
  "requesty/deepseek-v4-flash-0731@eu": { input: 0.14, output: 0.28 },
  "requesty/gemini-3.5-flash@eu": { input: 1.5, output: 9 },
  "requesty/claude-sonnet-4-6@eu": { input: 3.3, output: 16.5 },
  "requesty/gpt-4.1-mini@eu": { input: 0.44, output: 1.76 },
  "requesty/claude-haiku-4-5": { input: 1, output: 5 },
  "requesty/claude-opus-4-7@eu": { input: 5.5, output: 27.5 },
  "alibaba/qwen3-coder-480b-a35b-instruct": { input: 1.5, output: 7.5 },
  "alibaba/qwen3.7-plus": { input: 0.5, output: 3 },
  "alibaba/qwen3-vl-plus": { input: 0.2, output: 1.6 },
  "alibaba/qwen3-32b": { input: 0.7, output: 2.8 },
  "alibaba/qwen3.6-35b-a3b": { input: 0.248, output: 1.485 },
  "alibaba/qwen2-5-vl-72b-instruct": { input: 2.8, output: 8.4 },
  "alibaba/qwen-max": { input: 1.6, output: 6.4 },
  "alibaba/qwen3.5-plus": { input: 0.4, output: 2.4 },
  "novita-ai/google/gemma-4-26b-a4b-it": { input: 0.13, output: 0.4 },
  "novita-ai/google/gemma-4-31b-it": { input: 0.14, output: 0.4 },
  "novita-ai/zai-org/glm-4.6v": { input: 0.3, output: 0.9 },
  "novita-ai/zai-org/glm-5": { input: 1, output: 3.2 },
  "novita-ai/zai-org/glm-4.5-air": { input: 0.13, output: 0.85 },
  "novita-ai/zai-org/glm-5.1": { input: 1.38, output: 4.4 },
  "novita-ai/zai-org/glm-4.7-flash": { input: 0.07, output: 0.4 },
  "novita-ai/zai-org/glm-5.2": { input: 1.4, output: 4.4 },
  "openrouter/~openai/gpt-latest": { input: 5, output: 30 },
  "openrouter/~openai/gpt-mini-latest": { input: 0.75, output: 4.5 },
  "openrouter/cohere/command-r-08-2024": { input: 0.15, output: 0.6 },
  "openrouter/cohere/command-r-plus-08-2024": { input: 2.5, output: 10 },
  "openrouter/cohere/north-mini-code:free": { input: 0, output: 0 },
  "openrouter/nvidia/nemotron-3-ultra-550b-a55b:free": { input: 0, output: 0 },
  "openrouter/nvidia/nemotron-3-nano-30b-a3b": { input: 0.05, output: 0.2 },
  "openrouter/nvidia/nemotron-nano-9b-v2:free": { input: 0, output: 0 },
  "huggingface/google/gemma-4-26B-A4B-it": { input: 0.13, output: 0.4 },
  "huggingface/google/gemma-4-31B-it": { input: 0.14, output: 0.4 },
  "huggingface/thinkingmachines/Inkling-Small": { input: 0.5, output: 1.2 },
  "huggingface/thinkingmachines/Inkling": { input: 1, output: 4.05 },
  "huggingface/zai-org/GLM-5": { input: 1, output: 3.2 },
  "huggingface/zai-org/GLM-4.5": { input: 0.6, output: 2.2 },
  "huggingface/zai-org/GLM-4.5-Air": { input: 0.13, output: 0.85 },
  "huggingface/zai-org/GLM-4.5V": { input: 0.6, output: 1.8 },
  "perplexity-agent/nvidia/nemotron-3-super-120b-a12b": { input: 0.25, output: 2.5 },
  "perplexity-agent/google/gemini-2.5-flash": { input: 0.3, output: 2.5 },
  "perplexity-agent/google/gemini-3-flash-preview": { input: 0.5, output: 3 },
  "perplexity-agent/google/gemini-3.1-pro-preview": { input: 2, output: 12 },
  "perplexity-agent/google/gemini-2.5-pro": { input: 1.25, output: 10 },
  "perplexity-agent/moonshot-ai/kimi-k2.7-code": { input: 0.95, output: 4 },
  "perplexity-agent/moonshot-ai/kimi-k3": { input: 3, output: 15 },
  "perplexity-agent/xai/grok-4-1-fast-non-reasoning": { input: 0.2, output: 0.5 },
  "zai/glm-4.6v": { input: 0.3, output: 0.9 },
  "zai/glm-5": { input: 1, output: 3.2 },
  "zai/glm-4.5-air": { input: 0.2, output: 1.1 },
  "zai/glm-5.1": { input: 1.4, output: 4.4 },
  "zai/glm-4.7-flash": { input: 0, output: 0 },
  "zai/glm-5.2": { input: 1.4, output: 4.4 },
  "zai/glm-4.7-flashx": { input: 0.07, output: 0.4 },
  "zai/glm-4.6": { input: 0.6, output: 2.2 },
};
