import type { Provider, Turn, Usage } from "../providers/provider.ts";

// A task's turn array grows with every tool round-trip; past a point the model starts ignoring
// earlier instructions. compactTurns replaces everything but the most recent turns with one
// summary turn, generated by the same provider that's running the task.
const KEEP_RECENT = 4;

function describeTurn(t: Turn): string {
  if (t.role === "user") return `User: ${t.text}`;
  if (t.role === "tool") return `Tool results: ${t.results.map((r) => `${r.name} → ${r.output.slice(0, 200)}`).join("; ")}`;
  const calls = t.toolCalls.length ? ` [called ${t.toolCalls.map((c) => c.name).join(", ")}]` : "";
  return `Assistant: ${t.text}${calls}`;
}

export async function compactTurns(
  turns: Turn[],
  provider: Provider,
  keepRecent = KEEP_RECENT,
  onUsage?: (u: Usage) => void,
): Promise<Turn[]> {
  if (turns.length <= keepRecent) return turns;
  let cut = turns.length - keepRecent;
  // Never start the kept "recent" window on a tool-result turn: it references tool_call/tool_use
  // ids from the assistant turn immediately before it, and every provider rejects a payload where
  // that assistant turn is missing (dangling id / broken role alternation). A fixed-size tail slice
  // can land here whenever an odd number of turns precede it — e.g. agent.ts's injectInbox() adds
  // an extra user turn some rounds and not others, shifting the parity round to round.
  while (cut > 0 && turns[cut]!.role === "tool") cut--;
  const old = turns.slice(0, cut);
  const recent = turns.slice(cut);
  const transcript = old.map(describeTurn).join("\n");
  // A second, fully billed model call. Its tokens went entirely unrecorded, so /usage and /cost
  // understated real spend by exactly the amount compaction cost — and compaction fires on the
  // longest, most expensive conversations. onUsage lets the caller book it against the agent.
  const { text, usage } = await provider.send(
    "Summarize this conversation excerpt in 2-4 sentences: what was asked, what was done, what's still pending. Be concise.",
    [{ role: "user", text: transcript }],
    [],
  );
  if (usage) onUsage?.(usage);
  const summaryTurn: Turn = { role: "user", text: `[Earlier conversation summary]\n${text}` };
  return [summaryTurn, ...recent];
}
