import type { Provider, Turn, Usage } from "../providers/provider.ts";
import { inputIncludesCache } from "../providers/pricing.ts";

// A task's turn array grows with every tool round-trip; past a point the model starts ignoring
// earlier instructions. compactTurns replaces everything but the most recent turns with one
// summary turn, generated by the same provider that's running the task.
const KEEP_RECENT = 4;

function describeTurn(t: Turn): string {
  if (t.role === "user") return `User: ${t.text}`;
  if (t.role === "tool") return `Tool results: ${t.results.map((r) => `${r.name} → ${r.output.slice(0, 200)}`).join("; ")}`;
  const calls = t.toolCalls.length ? ` [called ${t.toolCalls.map((c) => c.name).join(", ")}]` : "";
  return `Assistant: ${t.text}${calls}`;
}

export async function compactTurns(
  turns: Turn[],
  provider: Provider,
  keepRecent = KEEP_RECENT,
  onUsage?: (u: Usage) => void,
): Promise<Turn[]> {
  if (turns.length <= keepRecent) return turns;
  let cut = turns.length - keepRecent;
  // Never start the kept "recent" window on a tool-result turn: it references tool_call/tool_use
  // ids from the assistant turn immediately before it, and every provider rejects a payload where
  // that assistant turn is missing (dangling id / broken role alternation). A fixed-size tail slice
  // can land here whenever an odd number of turns precede it — e.g. agent.ts's injectInbox() adds
  // an extra user turn some rounds and not others, shifting the parity round to round.
  while (cut > 0 && turns[cut]!.role === "tool") cut--;
  const old = turns.slice(0, cut);
  const recent = turns.slice(cut);
  const transcript = old.map(describeTurn).join("\n");
  // A second, fully billed model call. Its tokens went entirely unrecorded, so /usage and /cost
  // understated real spend by exactly the amount compaction cost — and compaction fires on the
  // longest, most expensive conversations. onUsage lets the caller book it against the agent.
  const { text, usage } = await provider.send(SUMMARY_PROMPT, [{ role: "user", text: transcript }], []);
  if (usage) onUsage?.(usage);
  // The summary is what the model says it remembers; the ledger is what actually happened. Both,
  // because they fail differently — a summarizer under a length budget drops file paths first, and
  // the path of the file you already edited is the single fact a resumed task most needs.
  const ledger = factsFrom(old);
  const summaryTurn: Turn = {
    role: "user",
    text: `[Earlier conversation summary]\n${text}${ledger ? `\n\n${ledger}` : ""}`,
  };
  return [summaryTurn, ...recent];
}

// Asking for "2-4 sentences" reliably produced 2-4 sentences that named nothing: no files, no
// decisions, no unresolved errors — so the turn after a compaction re-read files it had already
// read and re-made choices it had already made. Naming the sections is what gets them filled in.
const SUMMARY_PROMPT =
  "You are compacting a work log so the engineer who continues this task loses nothing. " +
  "Write under these exact headings, omitting any that have no content:\n" +
  "Goal: what was asked.\n" +
  "Done: what has actually been completed.\n" +
  "Decisions: choices made that later work must stay consistent with (names, formats, conventions, locations).\n" +
  "Open: what is unfinished, failing, or still to verify.\n" +
  "Be specific and name files, functions and errors exactly. Facts over prose, no preamble.";

// Recovered mechanically from the turns being dropped, not from the model. `wrote x`/`edited x`
// are the literal strings the sandbox returns, and an `error:` prefix is how every failed tool
// call comes back — so this is exact where a summary is merely likely.
const FILE_RESULT = /^(?:wrote|edited) (.+)$/;

function factsFrom(turns: Turn[]): string {
  const files = new Set<string>();
  const errors: string[] = [];
  for (const t of turns) {
    if (t.role !== "tool") continue;
    for (const r of t.results) {
      const m = FILE_RESULT.exec(r.output.trim());
      if (m) files.add(m[1]!);
      // Only the most recent few, and only the first line: a stack trace re-pasted into every
      // later turn is how a context window fills up in the first place.
      if (r.output.startsWith("error:")) errors.push(`${r.name}: ${r.output.split("\n")[0]!.slice(0, 160)}`);
    }
  }
  const parts: string[] = [];
  if (files.size > 0) parts.push(`Files changed so far: ${[...files].join(", ")}`);
  if (errors.length > 0) parts.push(`Recent tool errors:\n${errors.slice(-3).map((e) => `- ${e}`).join("\n")}`);
  return parts.join("\n");
}

// --- Ingestion-time capping -------------------------------------------------------------------
//
// Compaction runs after a reply, on that reply's usage, and BEFORE the tools it asked for have
// executed. So a turn that starts at 94% and reads a large file lands past 100% with no chance to
// compact first: the provider answers 400 "context length exceeded" and the run dies. The fix is
// to size each tool result to the room actually left, at the moment it enters the history.

// Deliberately pessimistic. Prose averages ~4 characters a token; code, JSON and minified text are
// nearer 3, and an underestimate here is the failure this exists to prevent.
const CHARS_PER_TOKEN = 3;
// However full the window is, every result keeps this much, so a nearly-full context degrades to
// short excerpts instead of blinding the model. Compaction is what makes real room, not this.
const MIN_RESULT_TOKENS = 1_000;
// A single result is never worth more than this to the model, full window or not — roughly 15–20k
// tokens. Applies to ordinary turns too, so one `find` or a dense file cannot dominate the history.
export const MAX_RESULT_CHARS = 60_000;

// The whole prompt of the request that produced `u`, cached part included. Anthropic reports
// input_tokens as only the uncached tail, so reading it alone under-counts a warm conversation by
// nearly all of it.
export function promptTokens(provider: string, u: Usage): number {
  const cached = u.cacheReadTokens ?? 0;
  return inputIncludesCache(provider) ? u.inputTokens : u.inputTokens + cached + (u.cacheWriteTokens ?? 0);
}

// Characters each of this turn's `calls` tool results may occupy: what is left below `ratio` of the
// window after the request that just returned and the reply it produced, shared between the calls.
export function resultBudgetChars(usedTokens: number, context: number, ratio: number, calls: number): number {
  if (context <= 0) return MAX_RESULT_CHARS;
  const room = context * ratio - usedTokens;
  const share = Math.max(MIN_RESULT_TOKENS, room / Math.max(1, calls));
  return Math.min(MAX_RESULT_CHARS, Math.floor(share * CHARS_PER_TOKEN));
}

// Keep the start and the end, drop the middle, and say so. The end is kept because it is where a
// failure summary or a file's final lines live; the note says how to ask for the part that was cut.
export function truncateMiddle(text: string, maxChars: number): string {
  if (text.length <= maxChars) return text;
  const keep = Math.max(0, maxChars);
  const head = Math.ceil(keep * 0.6);
  const tail = keep - head;
  const omitted = text.length - keep;
  return (
    `${text.slice(0, head)}\n[… ${omitted} characters omitted from the middle to keep this result inside the context window. ` +
    `Ask for a narrower slice — read_file offset/limit, grep, or a more specific command — to see them.]\n${tail > 0 ? text.slice(-tail) : ""}`
  );
}
