import type { Provider, Turn } from "../providers/provider.ts";

// A task's turn array grows with every tool round-trip; past a point the model starts ignoring
// earlier instructions. compactTurns replaces everything but the most recent turns with one
// summary turn, generated by the same provider that's running the task.
const KEEP_RECENT = 4;

function describeTurn(t: Turn): string {
  if (t.role === "user") return `User: ${t.text}`;
  if (t.role === "tool") return `Tool results: ${t.results.map((r) => `${r.name} → ${r.output.slice(0, 200)}`).join("; ")}`;
  const calls = t.toolCalls.length ? ` [called ${t.toolCalls.map((c) => c.name).join(", ")}]` : "";
  return `Assistant: ${t.text}${calls}`;
}

export async function compactTurns(turns: Turn[], provider: Provider, keepRecent = KEEP_RECENT): Promise<Turn[]> {
  if (turns.length <= keepRecent) return turns;
  const old = turns.slice(0, -keepRecent);
  const recent = turns.slice(-keepRecent);
  const transcript = old.map(describeTurn).join("\n");
  const { text } = await provider.send(
    "Summarize this conversation excerpt in 2-4 sentences: what was asked, what was done, what's still pending. Be concise.",
    [{ role: "user", text: transcript }],
    [],
  );
  const summaryTurn: Turn = { role: "user", text: `[Earlier conversation summary]\n${text}` };
  return [summaryTurn, ...recent];
}
